import { assetSecurityFixture } from "./test/assetSecurityFixture";
import { fileURLToPath } from "node:url";
import { playwright } from "@vitest/browser-playwright";
import { defineConfig, mergeConfig } from "vitest/config";

import viteConfig from "./vite.config";

const srcPath = fileURLToPath(new URL("./src", import.meta.url));

export default mergeConfig(
  viteConfig,
  defineConfig({
    plugins: [assetSecurityFixture()],
    resolve: {
      alias: {
        "~": srcPath,
      },
    },
    test: {
      include: [
        "src/components/WorkspaceMediaView.browser.tsx",
        "src/components/AssetImageGallery.browser.tsx",
        "src/hooks/useMigrateClientSettings.browser.ts",
        "src/components/FileViewPanel.browser.tsx",
        "src/hooks/inputSafety.browser.tsx",
        "src/components/ProfileSwitcher.browser.tsx",
        "src/components/ChatView.browser.tsx",
        "src/components/chat/WorktreeSetupCard.browser.tsx",
        "src/components/ComposerPromptEditor.browser.tsx",
        "src/components/ProjectCloneController.browser.tsx",
        "src/components/AgentsPanel.browser.tsx",
        "src/components/ThreadSidebar.browser.tsx",
        "src/components/AppTitlebar.browser.tsx",
        "src/components/ThreadRecencyController.browser.tsx",
        "src/components/ThreadStatusNotificationController.browser.tsx",
        "src/components/KeybindingsToast.browser.tsx",
        "src/components/DiffPanel.browser.tsx",
        "src/components/FileBrowserPanel.browser.tsx",
        "src/components/WebSocketConnectionSurface.browser.tsx",
        "src/components/settings/DisplayProfileSelector.browser.tsx",
        "src/components/settings/GithubAccountPanel.browser.tsx",
        "src/components/settings/SessionNotesSettings.browser.tsx",
        "src/components/settings/KeybindingEditor.browser.tsx",
        "src/components/settings/McpServersSettings.browser.tsx",
        "src/components/settings/ProviderInstanceCard.browser.tsx",
        "src/components/settings/SettingsRouteState.browser.tsx",
        "src/components/settings/categories/StorageSettings.browser.tsx",
        "src/components/profiles/ProfileCard.browser.tsx",
        "src/components/profiles/ProfilesSettingsPage.browser.tsx",
        "src/components/onboarding/HarnessValidationPanel.browser.tsx",
        "src/components/home/HomeMissionControl.browser.tsx",
        "src/components/prHub/PrDetailsTabs.browser.tsx",
        "src/components/prHub/PrLocalCheckout.browser.tsx",
        "src/components/prHub/PrQuickReview.browser.tsx",
        "src/components/prHub/PrInboxView.browser.tsx",
        "src/components/prHub/PrFocusView.browser.tsx",
        "src/components/usage/UsageDashboard.browser.tsx",
        "src/routes/-_chat.settings.browser.tsx",
        "src/routes/-_chat.index.browser.tsx",
        "src/components/chat/AssistantMessageActions.browser.tsx",
        "src/components/chat/AssistantQuoteToolbar.browser.tsx",
        "src/components/chat/ComposerPendingApprovalActions.browser.tsx",
        "src/components/chat/ClaudeTraitsPicker.browser.tsx",
        "src/components/chat/CodexTraitsPicker.browser.tsx",
        "src/components/chat/ChatHeader.browser.tsx",
        "src/components/chat/composer/ContextMeter.browser.tsx",
        "src/components/chat/CommandTranscriptCard.browser.tsx",
        "src/components/chat/ExpandedImagePreview.browser.tsx",
        "src/components/chat/MessagesTimeline.browser.tsx",
        "src/components/chat/NextTurnQueuePanel.browser.tsx",
        "src/components/chat/AsyncUserInputPanel.browser.tsx",
        "src/components/chat/ProviderInstanceModelPicker.browser.tsx",
        "src/components/chat/ProviderModelPicker.browser.tsx",
        "src/components/ui/toast.browser.tsx",
        "src/components/ui/sidebar.browser.tsx",
        "src/components/workflow/WorkflowCreateDialog.browser.tsx",
        "src/components/workflow/CodeReviewWorkflowView.browser.tsx",
        "src/components/workflow/WorkflowImplementDialog.browser.tsx",
        "src/components/workflow/WorkflowView.browser.tsx",
      ],
      browser: {
        enabled: true,
        provider: playwright(),
        instances: [{ browser: "chromium" }],
        headless: true,
      },
      testTimeout: 30_000,
      hookTimeout: 30_000,
    },
  }),
);
