/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/_chat";
import { Route as ChatIndexRouteImport } from "./routes/_chat.index";
import { Route as ChatSettingsRouteImport } from "./routes/_chat.settings";
import { Route as ChatThreadIdRouteImport } from "./routes/_chat.$threadId";
import { Route as ChatWorkflowWorkflowIdRouteImport } from "./routes/_chat.workflow.$workflowId";
import { Route as ChatCodeReviewWorkflowIdRouteImport } from "./routes/_chat.code-review.$workflowId";

const ChatRoute = ChatRouteImport.update({
  id: "/_chat",
  getParentRoute: () => rootRouteImport,
} as any);
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChatRoute,
} as any);
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ChatRoute,
} as any);
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: "/$threadId",
  path: "/$threadId",
  getParentRoute: () => ChatRoute,
} as any);
const ChatWorkflowWorkflowIdRoute = ChatWorkflowWorkflowIdRouteImport.update({
  id: "/workflow/$workflowId",
  path: "/workflow/$workflowId",
  getParentRoute: () => ChatRoute,
} as any);
const ChatCodeReviewWorkflowIdRoute = ChatCodeReviewWorkflowIdRouteImport.update({
  id: "/code-review/$workflowId",
  path: "/code-review/$workflowId",
  getParentRoute: () => ChatRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof ChatIndexRoute;
  "/$threadId": typeof ChatThreadIdRoute;
  "/settings": typeof ChatSettingsRoute;
  "/code-review/$workflowId": typeof ChatCodeReviewWorkflowIdRoute;
  "/workflow/$workflowId": typeof ChatWorkflowWorkflowIdRoute;
}
export interface FileRoutesByTo {
  "/$threadId": typeof ChatThreadIdRoute;
  "/settings": typeof ChatSettingsRoute;
  "/": typeof ChatIndexRoute;
  "/code-review/$workflowId": typeof ChatCodeReviewWorkflowIdRoute;
  "/workflow/$workflowId": typeof ChatWorkflowWorkflowIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_chat": typeof ChatRouteWithChildren;
  "/_chat/$threadId": typeof ChatThreadIdRoute;
  "/_chat/settings": typeof ChatSettingsRoute;
  "/_chat/": typeof ChatIndexRoute;
  "/_chat/code-review/$workflowId": typeof ChatCodeReviewWorkflowIdRoute;
  "/_chat/workflow/$workflowId": typeof ChatWorkflowWorkflowIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$threadId"
    | "/settings"
    | "/code-review/$workflowId"
    | "/workflow/$workflowId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/$threadId" | "/settings" | "/" | "/code-review/$workflowId" | "/workflow/$workflowId";
  id:
    | "__root__"
    | "/_chat"
    | "/_chat/$threadId"
    | "/_chat/settings"
    | "/_chat/"
    | "/_chat/code-review/$workflowId"
    | "/_chat/workflow/$workflowId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_chat": {
      id: "/_chat";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_chat/": {
      id: "/_chat/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ChatIndexRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/_chat/settings": {
      id: "/_chat/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof ChatSettingsRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/_chat/$threadId": {
      id: "/_chat/$threadId";
      path: "/$threadId";
      fullPath: "/$threadId";
      preLoaderRoute: typeof ChatThreadIdRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/_chat/workflow/$workflowId": {
      id: "/_chat/workflow/$workflowId";
      path: "/workflow/$workflowId";
      fullPath: "/workflow/$workflowId";
      preLoaderRoute: typeof ChatWorkflowWorkflowIdRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/_chat/code-review/$workflowId": {
      id: "/_chat/code-review/$workflowId";
      path: "/code-review/$workflowId";
      fullPath: "/code-review/$workflowId";
      preLoaderRoute: typeof ChatCodeReviewWorkflowIdRouteImport;
      parentRoute: typeof ChatRoute;
    };
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute;
  ChatSettingsRoute: typeof ChatSettingsRoute;
  ChatIndexRoute: typeof ChatIndexRoute;
  ChatCodeReviewWorkflowIdRoute: typeof ChatCodeReviewWorkflowIdRoute;
  ChatWorkflowWorkflowIdRoute: typeof ChatWorkflowWorkflowIdRoute;
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatCodeReviewWorkflowIdRoute: ChatCodeReviewWorkflowIdRoute,
  ChatWorkflowWorkflowIdRoute: ChatWorkflowWorkflowIdRoute,
};

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
