import type { SettingsItemDescriptor } from "../settingsSearch";

export const DISPLAY_SETTINGS_DESCRIPTORS = (
  [
    [
      "streaming",
      "Stream assistant messages",
      "Show output while a response is in progress.",
      "Stream assistant messages",
      ["tokens", "response"],
    ],
    [
      "file-links",
      "Open file links in code panel",
      "Open file links inside F5 instead of an external editor.",
      "Open file links in code panel",
      ["files", "editor", "preview"],
    ],
    [
      "word-wrap",
      "Wrap long code and table lines",
      "Wrap chat code, tables, diffs, and previews.",
      "Wrap long code and table lines",
      ["diff", "code", "table", "line wrap"],
    ],
    [
      "file-tree-limit",
      "File tree entry limit",
      "Set the maximum number of entries loaded in the Files panel.",
      "File tree entry limit",
      ["files", "explorer", "performance"],
    ],
    [
      "work-log-detail",
      "Work log detail level",
      "Choose essential, standard, or diagnostic work-log detail.",
      "Work log detail level",
      ["activity", "diagnostics", "tools"],
    ],
    [
      "work-log-category",
      "Work log category",
      "Show all work or filter the work log to one category.",
      "Work log category",
      ["activity", "filter", "tools"],
    ],
    [
      "workflow-expand",
      "Auto-expand workflows in sidebar",
      "Show workflow subthreads without opening them first.",
      "Auto-expand workflows in sidebar",
      ["workflow", "sidebar", "threads"],
    ],
    [
      "command-output",
      "Show command output in thread",
      "Display agent commands and output inline.",
      "Show command output in thread",
      ["terminal", "transcript", "shell"],
    ],
    [
      "command-expand",
      "Auto-expand command output",
      "Open command output automatically.",
      "Auto-expand command output",
      ["terminal", "transcript", "shell"],
    ],
    [
      "mcp-details",
      "Show MCP tool call details",
      "Display MCP inputs and results in expandable cards.",
      "Show MCP tool call details",
      ["tools", "server", "model context protocol"],
    ],
    [
      "mcp-expand",
      "Auto-expand MCP cards",
      "Open MCP cards automatically.",
      "Auto-expand MCP cards",
      ["tools", "server", "model context protocol"],
    ],
    [
      "reasoning",
      "Auto-expand reasoning",
      "Show model thinking inline instead of collapsed.",
      "Auto-expand reasoning",
      ["thinking", "analysis"],
    ],
    [
      "inline-diffs",
      "Show file diffs inline",
      "Display complete diffs for file changes in chat.",
      "Show file diffs inline",
      ["changes", "patch", "code"],
    ],
    [
      "runtime-warnings",
      "Runtime warnings",
      "Choose how much provider warning detail is shown.",
      "Runtime warnings",
      ["provider", "errors", "diagnostics"],
    ],
    [
      "provider-metadata",
      "Show provider metadata",
      "Display the active model, CLI version, and session details.",
      "Show provider metadata",
      ["model", "session", "version"],
    ],
    [
      "sidebar-preview",
      "Sidebar thread preview count",
      "Set how many threads appear before Show more.",
      "Sidebar thread preview count",
      ["sidebar", "threads", "limit"],
    ],
  ] as const
).map(([id, label, description, ariaLabel, keywords]) => ({
  id: `display.${id}`,
  category: "display" as const,
  label,
  description,
  keywords,
  targetSelector: `[aria-label="${ariaLabel}"]`,
})) satisfies ReadonlyArray<SettingsItemDescriptor>;
