import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ProjectMemorySavedPayload as ContractsProjectMemorySavedPayloadSchema,
  ProjectMemoryUpdatedPayload as ContractsProjectMemoryUpdatedPayloadSchema,
  ProjectMemoryDeletedPayload as ContractsProjectMemoryDeletedPayloadSchema,
  ProjectSkillsReplacedPayload as ContractsProjectSkillsReplacedPayloadSchema,
  ProjectWorkflowCreatedPayload as ContractsProjectWorkflowCreatedPayloadSchema,
  ProjectWorkflowDeletedPayload as ContractsProjectWorkflowDeletedPayloadSchema,
  ProjectWorkflowUpsertedPayload as ContractsProjectWorkflowUpsertedPayloadSchema,
  ProjectCodeReviewWorkflowCreatedPayload as ContractsProjectCodeReviewWorkflowCreatedPayloadSchema,
  ProjectCodeReviewWorkflowDeletedPayload as ContractsProjectCodeReviewWorkflowDeletedPayloadSchema,
  ProjectCodeReviewWorkflowUpsertedPayload as ContractsProjectCodeReviewWorkflowUpsertedPayloadSchema,
  ProjectInvestigationWorkflowCreatedPayload as ContractsProjectInvestigationWorkflowCreatedPayloadSchema,
  ProjectInvestigationWorkflowDeletedPayload as ContractsProjectInvestigationWorkflowDeletedPayloadSchema,
  ProjectInvestigationWorkflowUpsertedPayload as ContractsProjectInvestigationWorkflowUpsertedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadPinsReplacedPayload as ContractsThreadPinsReplacedPayloadSchema,
  ThreadLegacyPinsImportedPayload as ContractsThreadLegacyPinsImportedPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadTitleRegenerationStartedPayload as ContractsThreadTitleRegenerationStartedPayloadSchema,
  ThreadTitleRegeneratedPayload as ContractsThreadTitleRegeneratedPayloadSchema,
  ThreadTitleRegenerationFailedPayload as ContractsThreadTitleRegenerationFailedPayloadSchema,
  ThreadTitleRegenerationDiscardedPayload as ContractsThreadTitleRegenerationDiscardedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadTurnProcessingQuiescedPayload as ContractsThreadTurnProcessingQuiescedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTasksUpdatedPayload as ContractsThreadTasksUpdatedPayloadSchema,
  ThreadCompactRequestedPayload as ContractsThreadCompactRequestedPayloadSchema,
  ThreadCompactedPayload as ContractsThreadCompactedPayloadSchema,
  ThreadSessionNotesRecordedPayload as ContractsThreadSessionNotesRecordedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadCommandExecutionRecordedPayload as ContractsThreadCommandExecutionRecordedPayloadSchema,
  ThreadCommandExecutionOutputAppendedPayload as ContractsThreadCommandExecutionOutputAppendedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const ProjectMemorySavedPayload = ContractsProjectMemorySavedPayloadSchema;
export const ProjectMemoryUpdatedPayload = ContractsProjectMemoryUpdatedPayloadSchema;
export const ProjectMemoryDeletedPayload = ContractsProjectMemoryDeletedPayloadSchema;
export const ProjectSkillsReplacedPayload = ContractsProjectSkillsReplacedPayloadSchema;
export const ProjectWorkflowCreatedPayload = ContractsProjectWorkflowCreatedPayloadSchema;
export const ProjectWorkflowUpsertedPayload = ContractsProjectWorkflowUpsertedPayloadSchema;
export const ProjectWorkflowDeletedPayload = ContractsProjectWorkflowDeletedPayloadSchema;
export const ProjectCodeReviewWorkflowCreatedPayload =
  ContractsProjectCodeReviewWorkflowCreatedPayloadSchema;
export const ProjectCodeReviewWorkflowUpsertedPayload =
  ContractsProjectCodeReviewWorkflowUpsertedPayloadSchema;
export const ProjectCodeReviewWorkflowDeletedPayload =
  ContractsProjectCodeReviewWorkflowDeletedPayloadSchema;
export const ProjectInvestigationWorkflowCreatedPayload =
  ContractsProjectInvestigationWorkflowCreatedPayloadSchema;
export const ProjectInvestigationWorkflowUpsertedPayload =
  ContractsProjectInvestigationWorkflowUpsertedPayloadSchema;
export const ProjectInvestigationWorkflowDeletedPayload =
  ContractsProjectInvestigationWorkflowDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadPinsReplacedPayload = ContractsThreadPinsReplacedPayloadSchema;
export const ThreadLegacyPinsImportedPayload = ContractsThreadLegacyPinsImportedPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadTitleRegenerationStartedPayload =
  ContractsThreadTitleRegenerationStartedPayloadSchema;
export const ThreadTitleRegeneratedPayload = ContractsThreadTitleRegeneratedPayloadSchema;
export const ThreadTitleRegenerationFailedPayload =
  ContractsThreadTitleRegenerationFailedPayloadSchema;
export const ThreadTitleRegenerationDiscardedPayload =
  ContractsThreadTitleRegenerationDiscardedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadTurnProcessingQuiescedPayload =
  ContractsThreadTurnProcessingQuiescedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;
export const ThreadTasksUpdatedPayload = ContractsThreadTasksUpdatedPayloadSchema;
export const ThreadCompactRequestedPayload = ContractsThreadCompactRequestedPayloadSchema;
export const ThreadCompactedPayload = ContractsThreadCompactedPayloadSchema;
export const ThreadSessionNotesRecordedPayload = ContractsThreadSessionNotesRecordedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const ThreadCommandExecutionRecordedPayload =
  ContractsThreadCommandExecutionRecordedPayloadSchema;
export const ThreadCommandExecutionOutputAppendedPayload =
  ContractsThreadCommandExecutionOutputAppendedPayloadSchema;
