export const CODEX_MCP_OAUTH_LOGIN_TIMEOUT_SEC = 15 * 60;
export const CODEX_MCP_OAUTH_CLIENT_TTL_MS = (CODEX_MCP_OAUTH_LOGIN_TIMEOUT_SEC + 60) * 1000;
export const CODEX_MCP_OAUTH_LOGIN_REQUEST_TIMEOUT_MS = CODEX_MCP_OAUTH_CLIENT_TTL_MS;
