import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { COMPUTER_APP_TIERS, COMPUTER_BROWSER_IDS } from "@t3tools/shared/computerApps";
const root = fileURLToPath(new URL("..", import.meta.url));
const json = JSON.stringify({ tiers: COMPUTER_APP_TIERS, browsers: COMPUTER_BROWSER_IDS });
const files = [
  ["apps/desktop/native/computer-tiers.json", `${json}\n`],
  [
    "apps/desktop/native/macos/Sources/F5ComputerCore/ComputerTierTable.swift",
    `// Generated by scripts/generate-computer-tiers.ts. Do not edit.\nlet computerTierTableJSON = #"${json}"#\n`,
  ],
] as const;
for (const [name, contents] of files) {
  const path = resolve(root, name);
  if (process.argv.includes("--check")) {
    const actual = readFileSync(path, "utf8");
    const matches = name.endsWith(".json")
      ? JSON.stringify(JSON.parse(actual)) === json
      : actual === contents;
    if (!matches) throw new Error(`Computer tier table drift: ${name}`);
  } else writeFileSync(path, contents);
}
